
server:
  port: 8000
  servlet:
    context-path: /
    
spring:     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul
    username: cos
    password: bitc5600
  servlet:    multipart:      max-request-size: 50MB
      max-file-size: 50MB        
    
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

